kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvat-redis-pvc
  namespace: cvat
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-redis
  namespace: cvat
  labels:
    name: cvat-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat-redis
  template:
    metadata:
      labels:
        app: cvat-redis
    spec:
      imagePullSecrets:
      - name: registry-key
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: cvat-redis-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: cvat-redis-container
        image: hank997/cvat-redis:4.0-alpine
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: localtime
          mountPath: /etc/localtime
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: cvat-redis-svc
  namespace: cvat
  labels:
    name: cvat-redis-svc
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      name: cvat-redis
  selector:
    app: cvat-redis