apiVersion: v1
kind: Service
metadata:
  name: cvat-ui-svc
  namespace: cvat
  labels:
    name: cvat-ui-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: cvat-ui
  selector:
    app: cvat-ui