kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvat-data
  namespace: cvat
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
--- 

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvat-keys
  namespace: cvat
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvat-logs
  namespace: cvat
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvat-models
  namespace: cvat
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi