apiVersion: v1
kind: Service
metadata:
  name: cvat-svc
  namespace: cvat
  labels:
    name: cvat-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: cvat-8080
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: cvat-8443
  selector:
    app: cvat