

---
apiVersion: v1
kind: Service
metadata:
  name: cvat-proxy-svc
  namespace: cvat
  labels:
    name: cvat-proxy-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: cvat-proxy
  selector:
    app: cvat-proxy